name: snapshare_mobile
description: Share image application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.19.2 <3.0.0'

dependencies:
    cupertino_icons: ^1.0.2
    flutter:
        sdk: flutter
    flutter_dotenv: ^5.0.2
    google_fonts: ^4.0.3
    http: ^0.13.5
    provider: ^6.0.5
    shared_preferences: ^2.1.0

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
    - .env
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
